### ISSUE TITLE
Is it possible to pass a lnaguage code(s) to toc-extract-pages-ocr?

### ISSUE THREAD

**Issue by oatmealm** [dalanicolai/toc-mode#1]
Hi. Wonderful idea. Thanks a lot for this module.
Waned to ask if it's possible to invoke the OCR extraction controlling the language(s) to use?

**Comment by dalanicolai** [comment]
Hi, I did not implement this option yet. However, you can very easily jump to the definition of the `toc-extract-pages-ocr` (via C-h f), where you fill find the tesseract command. You can then just add the languages (and its flag) to the command e.g.:
```
(call-process "tesseract" nil (list buffer nil) nil file "stdout" "-l" "eng+nld" "--psm" "6")
```
where I added the flag `-l` and the languages english and dutch (`eng+nld`) to the command. Don't forget to re-evaluate the function before you call it.
(You can list the available languages in the terminal with `tesseract --list-langs`, although you were probably already aware of this)

Thanks for the question, I will probably implement this as a customizable variable soon...

**Comment by oatmealm** [comment]
Would be very helpful! I'm assuming the specialized buffers will not necessarily support rtl languages ar/fr/he etc... I would check it out tomorrow with the adapted command line arguments. I typically work with Hebrew, or Arabic documents, often without a text layer in the pdf nor a toc... which I used to manually add using MasterPDF. This is SO much better!

**Comment by dalanicolai** [comment]
I've implemented it right away (the package on github is updated already, but it will take about a day before it is updated on MELPA). Anyway, I have created a customizable variable `toc-ocr-languages`. You can list languages available on your system using `M-x toc-list-languages`. Would be great if you could test it, and let me know if you find some bug. I would be surprised if it all just works with arabic or hebrew. I tried to OCR an arabic text before but the result wasn't to good...

**Comment by oatmealm** [comment]
No problem. Using straight to install from github...

Evaluating `toc-list-languages` I get

```
(ara eng fra heb)
```

Evaluating, with Hebrew being the dominant language....

```
(setq toc-ocr-languages "heb+eng") 
```

<details><pre>
פרק  1
האוכלוסייה הערבית בישראל: נתוני יסוד
א. מבוא  1
ב. דמוגרפיה, שיעורי פריון, גילים, ריבוי טבעי,
תוחלת חיים, תמותת תינוקות, משקי בית  3
1. כללי  3
2. יישובים ותפרוסת אוכלוסין  6
3. שיעורי הפריון  10
4. גילים וו
5. ריבוי טבעי  12
6. תוחלת החיים  14
7. תמותת תינוקות  14
8. משקי הבית  15
ג. כוח העבודה  7
1. השתייכות לכוח העבודה האזרחי  17
2. מאפייני תעסוקה  18
3. הקשר בין רמת ההשכלה לבין שיעור ההשתייכות לכוח העבודה |  20
ד. רמת חיים, אבטלה, עוני  23
1. רמת החיים  23
2. רמת האבטלה  24
3. ממדי העוני  28
4. המדד החברתי-כלכלי של היישובים הערביים בישראל  30
ה. חינוך והשכלה  33
1. רמת ההשכלה  8
2. בתי ספר, כיתות וצפיפות תלמידים במערכת החינוך הערבית  36
3. שיעור הזכאות לתעודת בגרות ועמידה בדרישות הסף
של האוניברסיטאות  39
4. שיעורי נשירת תלסידים  41
5. סטודנטים באוניברסיטאות ובמכללות  43
מקורות  6
תרשימים
תרשים 1: אוכלוסיית אזרחי ישראל לפי דת, סוף שנת  2006
(לא כולל מזרח ירושלים)  4
תרשים 2: תפרוסת האוכלוסייה הערבית בישראל לפי סוג היישוב,
6 (לא כולל מזרח ירושלים)  7
תרשים 3: תפרוסת גאוגרפית של אוכלוסיית אזרחי ישראל
הערבים, 2006 (לא כולל מזרח ירושלים)  10
תרשים 4: שיעור בני ס-19 לפי דת וקבוצת אוכלוסייה,  12
תרשים 5: שיעור משקי הבית לפי מספר נפשות וקבוצות
אוכלוסייה,  16
תרשים 6 שינויים במשלח-היד של מועסקים ערבים
(בשנים נבחרות)  19
תרשים 7: משקי בית שבראשם שכיר, לפי עשירוני הכנסה
וקבוצות אוכלוסייה,  24
תרשים 8: רמת האבטלה לפי קבוצות אוכלוסייה (בשנים נבחרות)  6
תרשים 9: תחולת העוני לפי ההכנסה הפנויה: נפשות, משקי בית
וילדים, לפי קבוצות אוכלוסייה (בשנים נבחרות)  29
תרשים 10: התפלגות רמת ההשכלה באוכלוסייה הערבית
לפי דת,  36
תרשים 11: שיעורי נשירה בכיתות ט'"י"א ממערכת החינוך הערבית
(בשנים נבחרות)  42
לוחות
לוח 1: האוכלוסייה הערבית בישראל בשנים נבחרות
(במספרים ובאחוזים)  5
לוח 2: הרכב האוכלוסייה בערים המעורבות, סוף  8
לוח 3: שיעורי הפריון של נשים לפי דת וקבוצות אוכלוסייה
(בשנים נבחרות) וו
לוח 4: שיעורי הריבוי הטבעי לפי דת וקבוצות אוכלוסייה,  13
לוח 5: תוחלת חיים לפי מגדר וקבוצות אוכלוסייה
(שנים נבחרות)  14
לוח 6: שיעורי תמותת תינוקות לכל 1,000 לידות לפי דת
וקבוצות אוכלוסייה,  15
לוח 7: ממוצע נפשות במשק בית לפי קבוצות אוכלוסייה
(בשנים נבחרות)  16
לוח 8: שיעור ההשתייכות לכוח העבודה לפי דת, סמגדר
וקבוצות אוכלוסייה,  18
לוח 9: שיעור ההשתייכות לכוח העבודה בקרב ערבים לפי מגדר
ושנות לימוד,  21
לוח 10: רמת ההשכלה של כוח העבודה האזרחי לפי
קבוצות אוכלוסייה,  21
לוח 11: ממוצע הכנסה ברוטו לשכיר, לפי מגדר וקבוצות
אוכלוסייה,  23
לוח 12: רמת האבטלה לפי דת, מגדר וקבוצות אוכלוסייה,  25
לוח 13: הקשר בין רמת ההשכלה לבין רמת האבטלה
בקרב ערבים,  27
לוח 14: תחולת העוני בקרב משפחות עובדות לפי
ההכנסה הפנויה,  30
לוח 15: המדד החברתי-כלכלי של היישובים בישראל,  31
לוח 16: רכות ההשכלה של האוכלוסייה הערבית (בשנים נבחרות)  34
לוח 17: רמת ההשכלה לפי קבוצות אוכלוסייה ומגדר,  35
לוח 18: בתי ספר במערכת החינוך הערבית בישראל
(בשנים נבחרות)  37
לוח 19: צפיפות תלמידים בכיתה לפי סוג מערכת החינוך
(בשנים נבחרות)  39
לוח 20: שיעור זכאות לתעודת בגרות לפי דת וקבוצות אוכלוסייה
(בשנים נבחרות)  40
לוח 21: שיעור זכאות לתעודת בגרות לפי מגדר וסוג
מערכת החינוך,  40
לוח 22: שיעורי נשירת תלסידים במעבר מתשס"ז (2007/2006)
לתשס"ח (2008/2007) לפי סוג מערכת החינוך  41
לוח 23: שיעורי נשירת תלסידים במעבר מתשס"ז (2007/2006)
לתשס"ח (2008/2007) במערכת החינוך הערבית  41
לוח 24: סטודנטים ערבים באוניברסיטאות לפי תואר (בשנים נבחרות)  43
לוח 25: סטודנטים ערבים באוניברסיטאות לפי דת, מגדר
ותואר, 2004/  45
</pre></details>

Attaching the first page of the PDF (up to and including the line starting with "4 30..." in the result buffer).
 
In the PDF you'll see numbers on the right that are part of the topic headline, while the numbers on the left are the actual page numbers :)

![gnome-shell-screenshot-ZAYAQ0](https://user-images.githubusercontent.com/68159077/91629210-35e22c00-e9c7-11ea-8985-c117ac30a0d3.png)

1. I guess it doesn't "see" levels since it scans from left to right.

2. First two lines are the heading of the TOC. which you probably can't detect and is perfectly fine to edit manually AFAIC...!

One problem though, it'd be good if the cleanup buffer would support `'bidi-parapgraph-direction` so text will align correctly. Seems like it has no effect in this buffer even when set manually...

**Comment by dalanicolai** [comment]
Hi! It would be more handy, if possible, if you could provide .pdf instead of .png so I can test it right away (without converting first).
However, I think the reason that it does not 'detect levels' is due to tesseract not detecting it. You can either try to use `toc--cleanup-set-level-by-index` (which tries to guess levels from separators, i.e. dots by default). Or you can insert spaces manually to set levels.
I am happily surprised, but at least the basic functionality seems to work fine here for hebrew.

I am not familiar with bidi-paragraph-direction and I am not sure how it is supposed to work. But here it does have effect in the cleanup buffer, e.g. try `M-: (setq bidi-paragraph-direction 'left-to-right)` in the cleanup buffer.

**Comment by oatmealm** [comment]
I see. I know that tesseract is able to produce correct hocr for hebrew, but all the apps i've tried result in a mirrored (in correct) PDF when creating the text layer... I don't know if it's related.

Attaching the file. TOC (for chapter 1) is on page 15. It's a report with many sections, and each section has it's own TOC.

[sample-he.pdf](https://github.com/dalanicolai/toc-mode/files/5145467/sample-he.pdf)

**Comment by oatmealm** [comment]
About the `bidi-paragraph-direction`, in "real" text buffers (ie. fundamental, org-mode, markdown etc.) setting it to `nil, will make the text re-flow naturally, either right-to-left or left-to-right, depending on the script used.  I've tried setting it for the cleanup buffer, but it didn't respond, but now it does... sorry!

![gnome-shell-screenshot-4RTRP0](https://user-images.githubusercontent.com/68159077/91640561-cdbf3480-ea1e-11ea-9f6e-ef3316126c3d.png)

**Comment by dalanicolai** [comment]
Ah I don't know what you mean with mirrored text layer. But tesseract has many settings so you could just try a little with tesseract on the command line using the png image you uploaded above and using
`tesseract --help-extra` and then e.g. `tesseract example.png tesout -l heb --psm 4`. Try different psm settings and if you find some better setting then let me know.
Also tesseract can attach textlayers itself and produce pdf output (just type pdf behind the previous command e.g. `tesseract example.png tesout -l heb --psm 4 pdf`), so if it has correct hocr I guess it should correctly attach the text-layer.
Finally, in my package I just use the text output from tesseract (not hocr). But in english texts, tesseract recognizes indentations and outputs indented text. However, in the file you sent me there are indented lines also, but here tesseract does not produce indented text. It would be interesting to know if the hocr shows the indentation, and then why the text output does not show it.

**Comment by oatmealm** [comment]
> Ah I don't know what you mean with mirrored text layer.

It reverses the order of the letters in each individual word. 

I didn't really work with tessract directly though, but saw and discussed this issue elsewhere, such with the developers of gimagereader. The hocr they get back is correct but when they embed the text layer all the words are mirrored. 

I'll have a look again at the command line options though. Thanks!

> It would be interesting to know if the hocr shows the indentation, and then why the text output does not show it.
 
Do you need me to have a look? How will the indentation be expressed on the hocr's xml structure?

**Comment by dalanicolai** [comment]
I never worked with the hocr but you wrote that tesseract is able to output correct hocr, so I supposed this included indentation.
Thanks for offering to have a look, but I did not meant interesting for me. Just I meant that it would be remarkable if tesseract produces the correct hocr but then creates pdfs with a 'mirrored text layer'. So it is just interesting to hear about the text-layer result. Would be nice if you could post here if tesseract's pdf output has a correct or a mirrored text layer...
