### ISSUE TITLE
[REGRESSION?] Hard dependency on djvu

### ISSUE THREAD

**Issue by oatmealm** [dalanicolai/toc-mode#3]
FYI, Looks like recent changes might have introduced hard dependency of the `djvu` module. I didn't have it installed before, but now its absence will trigger the following message, when for example invoking `toc-extract-only`:

```
autoload-do-load: Symbol’s value as variable is void: djvu-read-mode-map
```

No problem when this module is installed.

**Comment by dalanicolai** [comment]
Ah, great! Thanks for reporting. I've added some keybindings, but should have made it check first if the keymaps exist. Anyway, should be fixed here, and on Melpa in about a day.

**Comment by oatmealm** [comment]
Seems to work! Thanks.
