### ISSUE TITLE
toc-extract-* into active buffer which might be read-only

### ISSUE THREAD

**Issue by oatmealm** [dalanicolai/toc-mode#4]
I'm not sure if I'm describing it correctly, but I've noticed that when I try running either `toc-extract-*` functions in a `pdf-view` buffer with noter's own minor mode enabled (I think it's `org-noter-doc`, I get this error message:

```
Buffer is read-only: #<buffer....
```

**Comment by oatmealm** [comment]
Just thinking, maybe the extract functions should output the cleanup intial state into a fresh buffer in a new split/popup window...?

**Comment by dalanicolai** [comment]
Hi, I use org-noter too (although I did not yet know about the minor mode, but I read about the `org-noter-create-skeleton` just today, which is quite awesome), but I do not experience any issues when I test with `org-noter-doc-mode` enabled. Maybe you could enable debug-on-error (`M-x toggle-debug-on-error`) and upload the backtrace?

**Comment by dalanicolai** [comment]
Also just today, I discovered another awesome and often more useful package (if I am allowed to say it like this;)... see [pdf.tocgen](https://krasjet.com/voice/pdf.tocgen/)

**Comment by oatmealm** [comment]
Hi! Yes, I use the skeleton generator too, awesome :) 

The problem I'm describing is when you run org-noter on an org file, which has the `NOTER_DOCUMENT` setup. 

It will load the PDF and open a seperate frame with a buffer containing the org-file. 

When you then add a note to the PDF (`org-noter-insert-precise-note`), it will create a subheading in the org file, where you can type the text.

The problem I've described happens in this type of buffer in which org-noter activates its minor modes: a PDF-View buffer with `org-noter-doc` and a specialized key map, etc. 

Running `toc-extract-only`  on such a buffer will produce this error.

`toggle-debug-on-error` does not produce any traces in this case for some reason...

Thanks for the link to pdf.tocgen!

**Comment by dalanicolai** [comment]
So the cause of the problem was that org-noter renamed the buffer pdf-buffer to the name `toc-extract-only` used for the text buffer (removing the .pdf extension), so it complained because it could not insert the text in the PDF buffer. Anyway, it now renames the buffer by changing the .pdf extension to .txt.

I have implemented the pdf.tocgen functionality also in the toc-mode package, it is described in the README how to use it.
