### ISSUE TITLE
`toc-gen-set-level`: `(Shell command succeeded with no output)`

### ISSUE THREAD

**Issue by nanjigen** [dalanicolai/toc-mode#5]
Absolutely great package. Thank you for your work.

I have in the past gotten the `toc-gen-set-level` command to work, but as described in the title, I get the following error when running this command from M-x while selecting a partial word:

`(Shell command succeeded with no output)`

No further information is given, and I see nothing in the `*Messages*` or `*Warnings*` buffer. No other windows are generated as is expected to continue the toc-gen process described in the readme.

Other commands, such as `toc-extract-pages` work as expected. 

I use Doom

**Comment by dalanicolai** [comment]
Hi, sorry for this late response, but I think that I never got notified about this issue. Maybe, I have to explicitly 'watch' the repo to get notified, I willl investigate it.
Anyway, if you did not solve the problem in the meantime, it seems normal to get that message
`(Shell command succeeded with no output)`. But you should check if a `recipe.toml` file got created in the document's directory.

Also, this package originally only extracted full text from selected (contents) pages, optionally via OCR. But then I discovered the [pdf.tocgen](https://pypi.org/project/pdf.tocgen/), so I just implemented a simple way to configure and run the pdf.tocgen commands. But, probably you already noticed that, you can can get the full pdf.tocgen functionality from the command line. If pdf.tocgen extract too much or too little text, than it is very worthwhile to study its documentation.

This `toc-mode` package is especially useful for documents for which pdf-tocgen does not work well (e.g. scanned or djvu documents).
